version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'keycloak-nest'
    ports:
      - 3000:3000
    command: sh ./docker-entrypoint.sh
    volumes:
      - .:/usr/app/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
